"""Task 3B: HTML Mirror Form Generator.

Generates standalone HTML files that replicate the document's structure
using <fieldset> grouping with pre-filled <input> fields.

Usage:
    writer = HtmlWriter()
    writer.write_all(documents, template, Path("output/html"))
"""

import html
import logging
from pathlib import Path

from extractly.models.template import MasterTemplate
from extractly.models.extraction import ExtractedDocument

logger = logging.getLogger(__name__)

# Clean, readable inline CSS for the HTML forms
_CSS = """
body {
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    max-width: 900px;
    margin: 40px auto;
    padding: 20px;
    background: #f5f5f5;
    color: #333;
}
h1 {
    color: #2c3e50;
    border-bottom: 2px solid #3498db;
    padding-bottom: 10px;
}
fieldset {
    background: #fff;
    border: 1px solid #ddd;
    border-radius: 8px;
    padding: 20px;
    margin-bottom: 20px;
}
legend {
    font-weight: bold;
    font-size: 1.1em;
    color: #2980b9;
    padding: 0 10px;
}
.field-row {
    display: flex;
    align-items: center;
    margin-bottom: 12px;
}
.field-row label {
    flex: 0 0 200px;
    font-weight: 600;
    color: #555;
}
.field-row input {
    flex: 1;
    padding: 8px 12px;
    border: 1px solid #ccc;
    border-radius: 4px;
    background: #fafafa;
    font-size: 14px;
}
.footer {
    text-align: center;
    color: #999;
    font-size: 12px;
    margin-top: 30px;
}
"""


class HtmlWriter:
    """Generates standalone HTML mirror forms for extracted documents.

    Each HTML file replicates the original document's structure using
    <fieldset> for sections and <input> for fields, pre-filled with
    extracted values.
    """

    def write_all(
        self,
        documents: list[ExtractedDocument],
        template: MasterTemplate,
        output_dir: Path,
    ) -> list[Path]:
        """Generate HTML files for all extracted documents.

        Args:
            documents: List of extracted documents.
            template: The MasterTemplate (defines section/field structure).
            output_dir: Directory to write HTML files to.

        Returns:
            List of paths to generated HTML files.
        """
        output_dir.mkdir(parents=True, exist_ok=True)
        paths: list[Path] = []

        for doc in documents:
            path = self.write_one(doc, template, output_dir)
            paths.append(path)

        logger.info("Generated %d HTML files in %s", len(paths), output_dir)
        return paths

    def write_one(
        self,
        document: ExtractedDocument,
        template: MasterTemplate,
        output_dir: Path,
    ) -> Path:
        """Generate a single HTML mirror form for one document.

        Args:
            document: The extracted document data.
            template: The MasterTemplate for structure.
            output_dir: Directory to write the HTML file.

        Returns:
            Path to the generated HTML file.
        """
        filename = Path(document.source_filename).stem + ".html"
        output_path = output_dir / filename

        html_content = self._render_html(document, template)
        output_path.write_text(html_content, encoding="utf-8")

        logger.info("HTML form generated: %s", output_path)
        return output_path

    def _render_html(
        self, document: ExtractedDocument, template: MasterTemplate
    ) -> str:
        """Render the full HTML document as a string.

        Args:
            document: The extracted data.
            template: The structural template.

        Returns:
            Complete HTML string.
        """
        title = html.escape(document.source_filename)
        fieldsets = self._render_fieldsets(document, template)

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title} — Extracted Data</title>
    <style>{_CSS}</style>
</head>
<body>
    <h1>{title}</h1>
    <form>
{fieldsets}
    </form>
    <div class="footer">
        Generated by Extractly — Document type: {html.escape(template.document_type)}
    </div>
</body>
</html>"""

    def _render_fieldsets(
        self, document: ExtractedDocument, template: MasterTemplate
    ) -> str:
        """Render all fieldsets (one per template section).

        Args:
            document: The extracted data.
            template: The structural template.

        Returns:
            HTML string containing all <fieldset> elements.
        """
        parts: list[str] = []

        for section in template.sections:
            fields_html = self._render_fields(document, section.name, section.fields)
            parts.append(
                f'        <fieldset>\n'
                f'            <legend>{html.escape(section.name)}</legend>\n'
                f'{fields_html}'
                f'        </fieldset>'
            )

        return "\n".join(parts)

    def _render_fields(
        self,
        document: ExtractedDocument,
        section_name: str,
        fields: list,
    ) -> str:
        """Render input fields for a section.

        Args:
            document: The extracted data.
            section_name: Name of the current section.
            fields: List of Field objects from the template.

        Returns:
            HTML string containing field rows.
        """
        parts: list[str] = []

        for field in fields:
            value = document.get_field_value(section_name, field.label)
            safe_label = html.escape(field.label)
            safe_value = html.escape(value)
            input_id = f"{section_name}-{field.label}".lower().replace(" ", "-")

            parts.append(
                f'            <div class="field-row">\n'
                f'                <label for="{html.escape(input_id)}">{safe_label}</label>\n'
                f'                <input type="text" id="{html.escape(input_id)}" '
                f'value="{safe_value}" readonly>\n'
                f'            </div>'
            )

        return "\n".join(parts) + "\n"
